name: flame_simple_platformer
description: A 2d platformer made using Flame engine

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flame: 1.17.0
  flame_audio: 2.10.1
  flame_tiled: 1.20.0
  flutter:
    sdk: flutter
  tiled: 0.10.2

dev_dependencies:
  flame_lint: 1.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/
